[build]
  command = "CI= npm run build"
  commanOrigin = "ui"
  publish = "/opt/build/repo/build"
  publishOrigin = "ui"
[[headers]]
  for= "/src/serviceWorker.js"
  [headers.values]
  cache-control= "max-age=0, no-cache, no-store, must-revalidate"
  headersOrigin= config
